# azure-pipelines-local.yml (example for self-hosted Windows agent)
trigger:
  - main

pool:
  name: 'Default'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      call npm ci
    displayName: 'Install dependencies'

  - script: |
      start /B npm run start
      timeout /t 10
      call npx playwright install --with-deps
      call npx playwright test --reporter="junit,html"
    env:
      PLAYWRIGHT_JUNIT_OUTPUT_NAME: 'junit-results.xml'
      PLAYWRIGHT_HTML_REPORT: 'playwright-report'
      CI: 'true'
    displayName: 'Run Playwright tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit-results.xml'
    condition: succeededOrFailed()
    displayName: 'Publish test results'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'playwright-report'
      artifactName: 'playwright-report'
    condition: succeededOrFailed()
    displayName: 'Publish Artifacts'
